---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: fortune-deployment
    labels:
        app: fortune
        version: v1

spec:
    replicas: 2
    selector:
        matchLabels:
            app: fortune-pod
            version: v1
    template:
        metadata:
            name: fortune-pod
            labels:
                app: fortune-pod
                version: v1
        spec:
            containers:
            - name: fortune
              image: stackupiss/fortune:v1
              imagePullPolicy: Always
              ports:
              - name: app-port
                containerPort: 3000

---
kind: Service
apiVersion: v1

metadata:
   name: mydb-svc
   namespace: myns
   labels:
      app: mydb-svc
      version: v1

spec:
   type: ClusterIP
   selector:
      app: mydb-pod
   ports:
   - port: 3306
     targetPort: mysql