---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: mydb-deploy
    namespace: myns
    labels:
        app: mydb-deploy
        version: v1

spec:
    replicas: 1
    selector:
        matchLabels:
            app: mydb-pod
            version: v1
    template:
        metadata:
            labels:
                app: mydb-pod
                version: v1
        spec:
            containers:
                - name: mydb
                  image: stackupiss/northwind-db:v1
                  imagePullPolicy: Always
                  ports:
                      - name: mysql
                        containerPort: 3306

---
kind: Service
apiVersion: v1

metadata:
    name: mydb-svc
    namespace: myns
    labels:
        app: mydb-svc
        version: v1

spec:
    type: ClusterIP
    selector:
        app: mydb-pod
    ports:
        - port: 3306
          targetPort: mysql
